export const ROUTES = [
  '/',
  '/main',
  '/members',
  '/members/professor',
  '/members/students',
  '/publications',
  '/publications/international-journal',
  '/publications/domestic-journal',
  '/publications/international-conference',
  '/publications/domestic-conference',
  '/projects',
  '/researches',
  '/board',
  '/board/news',
  '/board/seminar',
  '/board/photo',
  '/links'
];
